---
collections:
# Install ansible.posix Ansible Collection
- name: ansible.posix
  version: 1.3.0
  source: https://galaxy.ansible.com

# Install community.kubernetes Ansible Collection
- name: community.kubernetes
  version: 1.2.1
  source: https://galaxy.ansible.com

# Install community.general Ansible Collection
- name: community.general
  version: 3.6.0
  source: https://galaxy.ansible.com

# Install community.mysql Ansible Collection
- name: community.mysql
  version: 2.1.1
  source: https://galaxy.ansible.com

# Install amazon.aws Ansible Collection
- name: amazon.aws
  version: 2.0.0
  source: https://galaxy.ansible.com
