---
- name: Deploy Wildfly
  hosts: wildfly
  remote_user: ec2-user
  become: yes
  gather_facts: no
  vars:
    jboss_home_directory: /opt/jboss
    java_home_path: /usr/lib/jvm/java
    java_log_directory_path: /var/log/jboss
    java_opts: "-Xms1024m -Xmx20480m -XX:MaxPermSize=768m"
    java_path: /usr/bin/java
    jboss_home_path: /opt/jboss/wildfly
    wildfly_home: "{{ jboss_home_path }}"
    instance_name: jboss-wildfly
    wildfly_user: 'jboss'
    wildfly_group: 'jboss'
    wildfly_uid: 1001
    wildfly_gid: 1001
    wildfly_version: 24.0.0.Final
    wildfly_sha1: 391346c9ed2772647ff07aeae39deb838ee11dcf
    wildfly_config_base: standalone.xml
  environment:
    JAVA_HOME: "{{ java_home_path }}"
    WILDFLY_VERSION: "{{ wildfly_version }}"
    WILDFLY_SHA1: "{{ wildfly_sha1 }}"
    JBOSS_HOME: "{{ jboss_home_path }}"
    LAUNCH_JBOSS_IN_BACKGROUND: true
  collections:
    - middleware_automation.jcliff
  roles:
    - prereqs
    - deploy_wildfly
    - wildfly_systemd
  post_tasks:

    - name: "Check that service {{ instance_name }} is running"
      service:
        name: "{{ instance_name }}"
        state: started

    - name: "Check that port is open"
      wait_for:
        port: 8080
        host: "{{ item }}"
      loop:
        - localhost

    - name: "Check that server is responsive"
      get_url:
        url: "http://localhost:8080/"
        dest: /tmp/res.txt

    - file:
        state: absent
        path: /tmp/res.txt
      changed_when: false
