---
- hosts: jumpbox
  tasks:   
  - name: Download RHEL image
    get_url:
      url: http://www.opentlc.com/download/osp_advanced_networking/rhel-guest-image-7.2-20151102.0.x86_64.qcow2
      dest: /tmp/rhel.qcow2
    tags:
      - tested
  - os_image:
      cloud: ospcloud
      name: rhel-guest
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /tmp/rhel.qcow2
    tags:
      - tested
