---
windows_unattended_install:
  ansible_controller:
    group_id: '1'
    inventory_id: '1'
  hardening_requirements:
    - 'password_section'
    - 'account_lockout_section'
    - 'auditing_section'
    - 'registry_fixes_section'
  windows_update_category:
    - 'CritialUpdates'
    - 'DefinitionUpdates'
    - 'SecurityUpdates'
    - 'UpdateRollups'
  iso_build:
    build_directory: '/tmp/vmware_windows_iso'
    build_vm_default_disk_size_mb: '40000'
    build_vm_default_local_user: 'Administrator'
    build_vm_default_user_password: 'Supersecret1@3'
    build_vm_dns_server: '10.10.10.10'
    build_vm_ip: '10.10.10.12'
    build_vm_network_default_gateway: '10.10.10.1'
    build_vm_subnet_prefix: '24'
    unattended_iso_name: 'win2019_Dec2021.iso'
    unattended_iso_path: '/var/www/html/windows/unattended_iso'
    windows_server_iso_name: '17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso'
    windows_server_path: '/var/www/html/windows/windows_server_iso'
  vmware_cluster:
    cluster: 'cluster1'
    data_center: 'Datacenter1'
    datastore_name: 'datastore1'
    datastore_path: '/vmfs/volumes/datastore1'
    folder: '/Datacenter1/vm'
    guest_id: 'windows9_64Guest'
    network_name: 'VM Network'
    windows_base_vm:
      cpu: '2'
      memory_mb: '8192'
      disk_mb: '40960'
      name: 'windows_2019_Base_Dec2021'
      scsi: 'lsilogicsas'
  vmware_tools:
    esx_67u3_download_path: 'vmware/vmware_tools/version_67u3/VMware-tools-10.3.10-12406962-x86_64.exe'
  webserver:
    ip_address: '10.10.10.11'
    unattended_iso_download_directory: 'windows/unattended_iso'
    windows_server_iso_download_directory: 'windows/windows_server_iso/win_2019'
