---
- name: Generate Compliance Report
  block:
    - name: Clean Up Reports Directory if it exists
      file:
        path: reports
        state: absent
      run_once: yes
    
    - name: Create Reports Directory
      file:
        path: reports
        state: directory
        mode: 0755
      run_once: yes
    
    - name: Template Rendering
      template:
        src: individual_server_report.html.j2
        dest: "reports/z_{{ inventory_hostname }}_interim_report.html"

    - name: Create Interim Report
      template:
        src: consolidated_servers_report.html.j2
        dest: "reports/Consolidated_Servers_Report.html"
      run_once: yes
    
    - name: Consolidate Interim Report
      assemble:
        src: reports/
        dest: reports/Consolidated_Servers_Report.html
      run_once: yes
    
    - name: Generate Remaining Portion of Report
      template:
        src: consolidated_servers_report_last_block.html.j2
        dest: "reports/consolidated_servers_report_last_block.html"
      run_once: yes
    
    - name: Get the List of Interim Reports
      find:
        paths: reports/
        patterns: '*_interim_report.html'
      register: interim_reports_to_delete
      run_once: yes
    
    - name: Clean Up Interim Reports
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ interim_reports_to_delete.files }}"
      run_once: yes
    
    - name: Consolidate Final Report
      assemble:
        src: reports/
        dest: reports/Consolidated_Servers_Report.html
      run_once: yes
    
    - name: Final Clean Up
      file:
        path: reports/consolidated_servers_report_last_block.html
        state: absent
      run_once: yes

    - name: Send Email with Report
      mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ gmail_account }}"
        password: "{{ gmail_account_password }}"
        to: Anthony Lin <anthony.lin.test@gmail.com>
        subject: "Ansible Report for JBoss Compliance"
        body: "See attached for the Compliance Report"
        attach:
         - reports/Consolidated_Servers_Report.html
      run_once: yes
  delegate_to: localhost
  become: false
